name: Deploy do Projeto Vue

on:
  push:
    branches:
      - first-marathon 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'the-code-arena/package-lock.json'

      - name: Instalar dependências e Build
        working-directory: ./the-code-arena
        run: |
          npm install
          npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload do artefato (pasta dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './the-code-arena/dist'

      - name: Deploy final
        id: deployment
        uses: actions/deploy-pages@v4